site_name: Intermezzo
nav:
  - Entornos Virtuales : entornos_virtuales.md
  - La tortuga que dibuja : la_tortuga_que_dibuja.md
  - Bots de Telegram en Python : bots_de_telegram_en_python.md
  - ¿Que es PEP8 y por qué se debe implementar? :
      que_es_PEP8_y_por_que_se_debe_implementar.md
  - La función `divmod()` : divmod.md
  - Buenas Prácticas: buenas_practicas.md
theme: readthedocs

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: es
