site_name: Intermezzo
nav:
  - Entornos Virtuales : entornos_virtuales.md
  - La tortuga que dibuja : la_tortuga_que_dibuja.md
  - Bots de Telegram en Python : bots_de_telegram_en_python.md
theme: readthedocs

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: es
